# Generated by Django 5.0.6 on 2024-08-03 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='review',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='email',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
