# Generated by Django 5.0.6 on 2024-08-07 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_productreview_username_productreview_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='username',
        ),
        migrations.AddField(
            model_name='productreview',
            name='username',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
