# Generated by Django 5.0.6 on 2024-08-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_productreview_username_productreview_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='Comment',
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attribute_key',
        ),
        migrations.AlterModelTable(
            name='attributevalue',
            table='attribute_value',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productattribute',
            table='attribute',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
