# Generated by Django 5.0.6 on 2024-08-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
