# Generated by Django 5.0.6 on 2024-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
