# Generated by Django 5.0.6 on 2024-08-09 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rating_remove_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.OneToOneField(default=34, on_delete=django.db.models.deletion.CASCADE, to='app.comment'),
            preserve_default=False,
        ),
    ]
